FROM --platform=linux/amd64 mcr.microsoft.com/dotnet/sdk:8.0 AS testrunner

WORKDIR /app

COPY CardValidation.sln ./
COPY src ./src
COPY tests ./tests

RUN dotnet restore
RUN dotnet build --configuration Debug --no-restore

CMD ["dotnet", "test", "--configuration", "Debug", "--no-build"]
